# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        # Only write to the cache for builds on the 'main' and 'devel' branches. (Default is 'main' only.)
        # Builds on other branches will only read existing entries from the cache.
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/devel' }}
    - name: Grant execute permission for gradlew
      working-directory: ./TransifexNativeSDK
      run: chmod +x gradlew
    - name: Unit Test
      working-directory: ./TransifexNativeSDK
      run: ./gradlew test
    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: unitTestReports
        path: |
          TransifexNativeSDK/clitool/build/reports/tests/test/
          TransifexNativeSDK/common/build/reports/tests/test/
          TransifexNativeSDK/txsdk/build/reports/tests/
        if-no-files-found: warn
